### ISSUE TITLE
TypeError: unusable

### ISSUE THREAD

**Issue by mbrevda** [jonbern/fetch-retry#93]
When passing a `Request()` object to fetch-retry, retries fail with:

```
node:internal/deps/undici/undici:9658
          throw new TypeError("unusable");
          ^

TypeError: unusable
    at _Request.clone (node:internal/deps/undici/undici:9658:17)
    at wrappedFetch (/tmp/node_modules/fetch-retry/index.js:69:21)
    at Timeout._onTimeout (/tmp/node_modules/fetch-retry/index.js:127:11)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
```

This issue appears in node 2.8.0 [that includes](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.8.0:~:text=deps%3A%20update%20undici%20to%206.19.8%20(Node.js%20GitHub%20Bot)) [undici v6.19.8](https://github.com/nodejs/undici/compare/v6.19.7...v6.19.8), which includes [this PR](https://github.com/nodejs/undici/pull/3460) which is likely related.

To reproduce, run the following commands, which uses docker to run the test on different versions of node. The 2.7 one should run fine, the 2.8 should fail with the above error:

<details><summary>test.mjs</summary>

```js
import retry from 'fetch-retry';

const retryFetch = retry(globalThis.fetch, {
  retryDelay: (attempt) => Math.pow(2, attempt) * 5000,
  retryOn: (attempt, e) => {
    if (attempt >= 5) return false;
    console.log(`fetch: retrying, attempt ${attempt + 1}`, e);
    return true;
  },
});

await retryFetch(
  new Request(
    'https://github.com/fobarba345zfoba345rbazfobarbazfobar2345bazfobar2354bazfobarbazfobarbazfobarbaz',
    {method: 'POST', body: 'foo=bar'},
  ),
);
```

</details> 

```
docker run -it --rm -v./:/tmp node:22.7.0-alpine3.19 node /tmp/test.mjs
docker run -it --rm -v./:/tmp node:22.8.0-alpine3.19 node /tmp/test.mjs
```

When running locally, here is what I get:

```sh
➜  web git:(master) ✗ docker run -it --rm -v./:/tmp node:22.7.0-alpine3.19 node /tmp/test.mjs
fetch: retrying, attempt 1 null
fetch: retrying, attempt 2 null
fetch: retrying, attempt 3 null
fetch: retrying, attempt 4 null
fetch: retrying, attempt 5 null
➜  web git:(master) ✗ docker run -it --rm -v./:/tmp node:22.8.0-alpine3.19 node /tmp/test.mjs
fetch: retrying, attempt 1 null
fetch: retrying, attempt 2 null
node:internal/deps/undici/undici:9658
          throw new TypeError("unusable");
          ^

TypeError: unusable
    at _Request.clone (node:internal/deps/undici/undici:9658:17)
    at wrappedFetch (/tmp/node_modules/fetch-retry/index.js:69:21)
    at Timeout._onTimeout (/tmp/node_modules/fetch-retry/index.js:127:11)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)

Node.js v22.8.0
```

**Comment by zoli-kasa** [comment]
this seems to be the root cause: https://github.com/nodejs/undici/issues/4150

**Comment by mbrevda** [comment]
In that case, this can be closed

**Comment by zoli-kasa** [comment]
The problem here is that `fetch-retry` does not catch that error, and it becomes an unhandled exception, causing server failures. I've wrapped the clone in a try-catch https://github.com/jonbern/fetch-retry/pull/97
